# Generated by Django 5.1.7 on 2025-04-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_profile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lesson",
            new_name="Topic",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="lesson",
            new_name="topic",
        ),
        migrations.RenameField(
            model_name="quiz",
            old_name="lesson",
            new_name="topic",
        ),
    ]
