# Generated by Django 5.2 on 2025-04-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_language_question_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(default='Explanation coming soon.'),
        ),
    ]
