# Generated by Django 5.2 on 2025-04-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course_students_alter_activity_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_password',
            field=models.CharField(blank=True, help_text='Set a password students must enter to join.', max_length=20, null=True),
        ),
    ]
