# Generated by Django 5.2 on 2025-04-23 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_course_enrollment_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('trace', 'Tracing')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiztemplate',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('trace', 'Tracing')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('explanation', models.TextField()),
                ('choice_a', models.TextField()),
                ('choice_b', models.TextField()),
                ('choice_c', models.TextField()),
                ('choice_d', models.TextField()),
                ('correct_choice', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TracingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('explanation', models.TextField()),
                ('code_snippet', models.TextField()),
                ('expected_output', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
