# Generated by Django 5.2 on 2025-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_quiz_question_type_quiztemplate_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tracingquestion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tracingquestion',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='tracingquestion',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
