# Generated by Django 5.2 on 2025-04-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_multiplechoicequestion_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracingquestion',
            name='code_snippet',
        ),
    ]
