# Generated by Django 5.2 on 2025-04-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_tracingquestion_code_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('tracing', 'Tracing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='quiztemplate',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('tracing', 'Tracing')], max_length=30),
        ),
    ]
